image: docker:latest

services:
  - docker:dind
variables:
  BUCKET_NAME: saber-bucket # Your bucket name
stages:
  - build
  - deploy
build:
  stage: build
  script:
    - echo "building"
    - docker build -t sabersalhi/docker-react .
  artifacts:
    paths:
      - build
deploy:
  stage: deploy
  only:
    - master
  script:
    - aws s3 cp --recursive ./build s3://${BUCKET_NAME}
