image: docker:latest
services:
      - docker:dind
stages:
  - test
  - build
  - deploy
test:
  stage: test
  script:
    - yarn
    - CI=true yarn test
build:
  stage: build
  script:
    - echo "building"
    - mkdir build
  artifacts:
    paths:
      - build/
deploy:
  stage: deploy
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - eval $(aws ecr get-login --no-include-email --region $AWS_REGION | sed 's|https://||')
    script:
        - aws s3 cp build/ s3://$BUCKET_NAME/ --recursive --include "*"
