image: docker:latest

services:
  - docker:dind
variables:
  BUCKET_NAME: saber-bucket # Your bucket name
stages:
  - build
  - deploy
build:
  image: node:10-alpine
  stage: build
  script:
    - echo "building"
    - docker build -t sabersalhi/docker-react -f- <<EOF .
  artifacts:
    paths:
      - build
deploy:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - aws s3 cp --recursive ./build s3://${BUCKET_NAME}
