image: node:latest
variables:
  BUCKET_NAME: saber-bucket # Your bucket name
stages:
  - build
  - deploy
build:
  image: docker:18
  stage: build
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
  script:
    - echo "building"
    - docker build -t sabersalhi/docker-react -f DockerFile.dev .
    - docker run sabersalhi/docker-react yarn build
  artifacts:
    paths:
      - build/
deploy:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws rm s3://{BUCKET_NAME} --recursive
    - aws s3 sync build/  s3://${BUCKET_NAME} --acl public-read
