image: docker:latest

services:
  - docker:dind
variables:
  BUCKET_NAME: saber-bucket # Your bucket name
stages:
  - build
  - deploy
build:
  stage: build
  script:
    - echo "building"
    - docker build -t sabersalhi/docker-react  .
  artifacts:
    paths:
      - build/
deploy:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://${BUCKET_NAME} --recursive
    - aws s3 sync ./build  s3://${BUCKET_NAME} --acl public-read
