image: node:10.20.1

stages:
  - test
  - build
  - deploy
test:
  stage: test
  script:
    - yarn
    - CI=true yarn test
build:
  stage: build
  script:
    - echo "building"
    - mkdir build
  artifacts:
    paths:
      - build/
deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest # see the note below
  script:
    - aws s3 cp _site s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
