# https://hub.docker.com/r/library/node/tags/
image: node:latest
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#AWS access keys stored as secret variables
variables:
  BUCKET_NAME: docker-learn
#AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#This declares the pipeline stages
stages:
  - build
  - test
  - deploy
cache:
  paths:
    - node_modules/
build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/
test:
  stage: test
  script:
    - echo "Running react test suite......"
deploy:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://${BUCKET_NAME} --recursive
    - aws s3 cp --recursive ./build s3://${BUCKET_NAME}
